apiVersion: v1
kind: Service
metadata:
  name: poodle-mysql
  labels:
    app: poodle
    chart: {{ include "poodle-appx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: mysql
      protocol: TCP
      name: poodle-mysql
  selector:
    app: poodle
    release: {{ .Release.Name }}
